mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - name: windows
    server: 172.22.130.227
    port: 10809
    type: http
    alterId: 2
rules:
- MATCH, windows
