#!/bin/bash


# 打印上边框
echo "┌───────────────────────────────────────────────┐"

# 打印框内内容，并使用绿色字体
echo -e "│ ${GREEN}服务器联网2.0 by Haolong Ma${NC}                   │"
echo -e "│ ${GREEN}该软件遵守GPLv3开源协议${NC}                       │"
echo -e "│ ${GREEN}如有任何问题，请联系作者${NC}                      │"

# 打印下边框
echo "└───────────────────────────────────────────────┘"

echo "输入你要安装的包:"
read packages

ip=$(cat ~/.config/ip.txt)
port=$(cat ~/.config/port.txt)

http_proxy="$ip:$port" all_proxy="$ip:$port" pip install "$packages" -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com/pypi/simple

